### PR TITLE
fix(README.md): Add NPM instructions

### LINKED ISSUE #1: Can this also live on NPM?
Since Bower is no longer being maintained I think it would make more sense to host this library on NPM or at least host it on both.

### PR DESCRIPTION
**Pull request by benoror**
Fixes #1

### CODE REVIEW

**Comment by toddmotto** [comment]
Thank you! :)

**Comment by mattdsteele** [comment]
Heads up - these NPM instructions don't work with NPM standalone - they use Git under the hood to pull things down. This doesn't work in environments like mine where we install NPM but not git.

It'd be preferable to actually publish this natively to NPM - if you'd like I can do it and add @toddmotto as an owner, just let me know!

**Comment by benoror** [comment]
@mattdsteele already did it:

https://www.npmjs.com/package/angular-component

@toddmotto can't find your npm username, mind sharing it?

**Comment by toddmotto** [comment]
Ah, thanks for this guys. "toddmotto" should be the username!

On 8 December 2015 at 17:19, Benjamin Orozco notifications@github.com
wrote:

> @mattdsteele https://github.com/mattdsteele already did it:
> 
> https://www.npmjs.com/package/angular-component
> 
> @toddmotto https://github.com/toddmotto can't find your npm username,
> mind sharing it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toddmotto/angular-component/pull/2#issuecomment-162950481
> .

## 

@toddmotto

**Comment by benoror** [comment]
np :smile: done

**Pull request merged**
