### PR TITLE
feat: Add 'isFirstChange' function to $onChanges hook changes object

### PR DESCRIPTION
**Pull request by bmcalister**
- added the isFirstChange function to the changes object passed to the $onChanges hook.
- Built dist files.

### CODE REVIEW

**Comment by toddmotto** [comment]
Hey Brian! I'm actually working on a separate branch to address a few issues, including this features, tests, and ensuring things are 100% feature complete. The `isFirstChange` is located here, and it's taken from the actual Angular source code: https://github.com/toddmotto/angular-component/blob/es6-and-tests/src/angular-component.js#L25-L31

**Comment by bmcalister** [comment]
oh I see, thanks for the heads-up!

**Comment by toddmotto** [comment]
If you've got some time to help get the features fully working, lemme know :) there's a test currently failing on the branch that I need to look at. :)

**Comment by bmcalister** [comment]
yep, are you referring to this: https://github.com/toddmotto/angular-component/blob/es6-and-tests/src/angular-component.js#L155-L167 ?

**Comment by toddmotto** [comment]
Partly that, there is an issue currently which fails a test to do with the $digest loop. It's to do with the queueing situation that Angular uses internally. But yeah, there's a bit of work that needs doing on the new branch if you're open to helping out! 💃

**Pull request closed without merging**
