### PR TITLE
Bugfix $on init trigger before on way binding

### PR DESCRIPTION
**Pull request by strokyl**
Contrary to what specify angular 1.5 documentation, when using angular 1.3 with this poly-fill, `$onInit` is called before one way binding are done.
This is very annoying because this force to place initialisation code on `$onChanges` and to check initialisation has not been done yet.

I could not find the unit-test file mentioned in the contribution part of the README.

### CODE REVIEW

**Comment by 807811b0-1373-11e5-b60b-1697f925ec7b** [comment]
See also https://github.com/angular/angular.js/issues/14433

**Comment by chamerling** [comment]
Hi @toddmotto,

Any chance to see this PR merged?

Thx a lot

**Comment by strokyl** [comment]
The thing is that he already fix this bug but on the following branch:
 - https://github.com/toddmotto/angular-component/tree/es6-and-tests
So the question is when does this branch is going to be merge/become the new master. If this will be in a long time, it would be great to merge my PR in the meanwhile.

**Comment by jeroenroumen** [comment]
Hey @toddmotto 

Would you consider merging this PR request?

Thanks ;)

**Comment by lbickston-rgi** [comment]
@toddmotto would you consider bumping the version?

**Pull request merged**
