### PR TITLE
Align with latest NG 1.5 changes

### PR DESCRIPTION
**Pull request by borislit**
Set $ctrl as default controllerAs param and removed option to configure scope (set it isolated by default).

All this in order to be compliant with latest changes to angular 1.5:
https://github.com/angular/angular.js/pull/13710

### CODE REVIEW

**Comment by toddmotto** [comment]
Awesome, would you be able to run `npm i` and then `gulp` to generate the `/dist` files please, we could bump this to `0.0.3` inside `package.json` too? :)

**Comment by borislit** [comment]
@toddmotto  Sure. Ill push in few minutes

**Comment by toddmotto** [comment]
Cheers dude, I'll update the Readme unless you have time (see changelog at bottom) :)

**Comment by borislit** [comment]
@toddmotto  pushed the dist files. I dont mind changing README, but ill have to do it a bit later :)
Lets see who gets there first :)

Glad to help :)

**Pull request merged**
