### PR TITLE
Add support for require object and $onInit controller method

### LINKED ISSUE #17: Add support for `require` object and $onInit controller method
Technically they are the features of directives and not components, but it would require too much fragile patching in versions prior to 1.5.

Directives can live fine without them, but they are essential for [intercomponent communication](https://docs.angularjs.org/guide/component#intercomponent-communication), components have no alternatives to `link` and thus are barely usable without them.

Can we add them, please?

### PR DESCRIPTION
**Pull request by bisubus**
Closes #17

### CODE REVIEW

**Comment by toddmotto** [comment]
Okay, we have some new things to consider before going further on this, I've held off merging as I knew more lifecycle hooks were coming. I think we could monkey patch the this.$postLink function and run it as `link` internally, $onDestroy would be super easy using the `$scope.$on('$destroy')` event, what do you think? See commit in v1.5.3 adding more hooks: https://github.com/angular/angular.js/commit/9cd9956dcbc8382e8e8757a805398bd251bbc67e

**Comment by bisubus** [comment]
@toddmotto That's great news, thanks, I've missed 'link' in components. Yes, $postLink and $onDestroy seem to be one-liners. I'm not sure if $onChanges is worth it, there is already a lag on binding features in pre-1.5, adding this one may be costly.

**Comment by toddmotto** [comment]
I've just pushed the $postLink and $onDestroy lifecycle hooks :)

**Comment by bisubus** [comment]
Nice. It is better to launch $onDestroy in prelink right after $onInit, this is where it originally belongs
https://github.com/angular/angular.js/blob/master/src/ng/compile.js#L2446

**Comment by toddmotto** [comment]
Consider it done! Just pushed the change. Nice spot. Thanks!

**Pull request merged**
